server {
    listen 0.0.0.0:8080;
    server_name localhost;

    location / {
        return 301 /index.html;
    }

    # Oops, forgot a semicolon here!
    location /index.html {
        allow_methods GET
        alias .;
    }
}
