server {
    listen 0.0.0.0:8080;
    server_name localhost;

    # Redirect requests for the absolute root to /index.html
    location / {
        return 301 /index.html;
    }

    # Standard location block for your actual files
    location /index.html {
        allow_methods GET;
        alias .;
    }
}
